In [2]:
a=1 ; print(type(a))

<class 'int'>


In [3]:
a=1 ; a =float(a); print(type(a))

<class 'float'>


In [4]:
a=1 ; a=int(a) ; print(type(a))

<class 'int'>


#### int는 정수고, float는 소수점이 있는 수다. (1.0도 float다.)

In [19]:
a='123';print(type(a));print(a[1])

<class 'str'>
2


## string

In [6]:
a='123';a=list(a);print(type(a));print(a);print(a[2])

<class 'list'>
['1', '2', '3']
3


In [7]:
a=[1,'2',[3,'4']];print(type(a));print(a[0]);print(a[1]);print(a[2])

<class 'list'>
1
2
[3, '4']


#### list! 순서를 나타날때 0은 첫번째, 1은 두번째다.

In [11]:
a= {"a":"apple","b":"orange","c":2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


#### dict라는 class인데, 중괄호를 쓰며 사전처럼 인덱스와 내용을 한꺼번에 볼 수 있다. 콜론을 써야된다는 점!

In [12]:
a=[(1,2,3),(3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

In [14]:
import numpy as np
b=np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


#### numpy에서 가져오는 것(아나콘다를 깐 이유) as np로 해줘야하면 array를 사용한 것이다. 행렬을 만드는 것인데, 이것은 완벽한 행렬이 아니다.

In [15]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


#### 원래 2 by 3 랑 2 by 3이랑 곱하면 오류가 생기는게 당연한 건데 이건 행렬이 아니라 곱해지는 것

In [16]:
c=np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


#### array가 아니라 matrix를 써서 행렬로 만드는 과정

In [17]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

#### 역시 행렬이 곱해지지 않는다.

In [18]:
c*c.T

matrix([[14, 19],
        [19, 73]])

#### c.T는 c를 transpose해준 것이므로 3 by 2 로 만들어진다. 결국, 곱해질 수 있게 변한 것이다.